version: "3"

services:
  kutt:
    image: kutt
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    ports:
      - "10000:10000"
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    volumes:
      - ./.env:/usr/src/app/.env

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
